return {
	["1"]	= {Outfits = {"Eskimo"}; Hats = {"Eskimo Hood", "Eskimo Hood Alt", "Verified"}; Auras = {"Robux"}};
	["2"]	= {XPBoost = {"10% XP Boost"}};
	["3"]	= {Backpacks = {"Survivor"}};
	["4"]	= {Currency	= {"100 Tickets"}};
	["5"]	= {Emotes = {"Fist Pump"}};
	["6"]	= {Outfits = {"Blue Winter Jacket"}; Hats = {"Blue Winter Hat"}};
	["7"]	= {Faces = {"Suave"}};
	["8"]	= {KillEffects = {"Freeze"}};
	["9"]	= {Currency	= {"100 Tickets"}};
	["10"]	= {Hats = {"Plaid Ushanka"}};
	["11"]	= {Emotes = {"Chill"}};
	["12"]	= {Backpacks = {"Hiker"}};
	["13"]	= {Hats = {"Ski Goggles"}};
	["14"]	= {Currency	= {"100 Tickets"}};
	["15"]	= {Outfits = {"Guest"}; Hats = {"Wonky Hat"}};
	["16"]	= {KillEffects = {"Anti Gravity"}};
	["17"]	= {Auras = {"Blue Pulse"}};
	["18"]	= {Backpacks = {"Retro Green"}};
	["19"]	= {Currency	= {"100 Tickets"}};
	["20"]	= {Aura	= {"Yellow Surge"}};
	["21"]	= {Hats = {"Yeti Headphones"}};
	["22"]	= {XPBoost = {"10% XP Boost"}};
	["23"]	= {KillEffects = {"Robux"}};
	["24"]	= {Currency	= {"100 Tickets"}};
	["25"]	= {Outfits = {"Builderman"}; Hats = {"Orange Hard Hat"}; Faces = {"Chuckle"}};
	["26"]	= {Armors = {"Spikes"}};
	["27"]	= {Hats = {"Wizard Glasses"}};
	["28"]	= {Emotes = {"Dribble"}};
	["29"]	= {Currency	= {"100 Tickets"}};
	["30"]	= {Backpacks = {"Climber"}};
	
	["31"]	= {Outfits = {"Zombie"}; Hats = {"Brain"}; Faces = {"Zombie"}};
	["32"]	= {Backpacks = {"Potion Seller"}};
	["33"]	= {Faces = {"Worried"}};
	["34"]	= {Currency	= {"100 Tickets"}};
	["35"]	= {Emotes = {"Situps"}};
	["36"]	= {Outfits = {"Radioactive"}; Hats = {"Radioactive Goggles", "Radioactive Headphones"}};
	["37"]	= {Backpacks = {"Megapack"}};
	["38"]	= {KillEffects = {"Blue Glow"}};
	["39"]	= {Currency	= {"100 Tickets"}};
	["40"]	= {Hats = {"Red Beret"}};
	["41"]	= {Emotes = {"Tough"}};
	["42"]	= {XPBoost = {"10% XP Boost"}};
	["43"]	= {Hats = {"Eyepatch"}};
	["44"]	= {Currency	= {"100 Tickets"}};
	["45"]	= {Outfits = {"Mint Overalls"}; Hats = {"Mint Hair"}; Faces = {"Crumbs"}};
	["46"]	= {KillEffects = {"Pink Slice"}};
	["47"]	= {Armors = {"Assassin"}};
	["48"]	= {Backpacks = {"Alien"}};
	["49"]	= {Currency	= {"100 Tickets"}};
	["50"]	= {Auras = {"Pink Surge"}};
	["51"]	= {Hats = {"Snake Eyes"}};
	["52"]	= {Faces = {"Scar"}};
	["53"]	= {KillEffects = {"Red Glow"}};
	["54"]	= {Currency	= {"100 Tickets"}};
	["55"]	= {Outfits = {"Red Cat Hoodie"}; Hats = {"Red Cat Hood"}};
	["56"]	= {Hats = {"Neon Bandit Mask"}};
	["57"]	= {Hats = {"Trashcan Helmet"}};
	["58"]	= {Emotes = {"Applause"}};
	["59"]	= {Currency	= {"100 Tickets"}};
	["60"]	= {Backpacks = {"Robot"}};
	
	["61"]	= {Outfits = {"DIY Robot"}; Hats = {"DIY Robot"}; Faces = {"Robot Smile"}};
	["62"]	= {XPBoost = {"10% XP Boost"}};
	["63"]	= {Hats = {"TV Head"}};
	["64"]	= {Currency	= {"100 Tickets"}};
	["65"]	= {Emotes = {"Hover"}};
	["66"]	= {Outfits = {"Red Alien"}; Hats = {"Red Antennae"}; Faces = {"Ambassador"}};
	["67"]	= {Hats = {"Scuba Goggles"}};
	["68"]	= {KillEffects = {"Green Glow"}};
	["69"]	= {Currency	= {"100 Tickets"}};
	["70"]	= {Hats = {"Bear Mask"}};
	["71"]	= {Emotes = {"Pow"}};
	["72"]	= {Backpacks = {"Neon Adventurer"}};
	["73"]	= {Faces = {"Wink"}};
	["74"]	= {Currency	= {"100 Tickets"}};
	["75"]	= {Outfits = {"Crimson Ninja"}; Hats = {"Crimson Ninja"}; Faces = {"Sneaky"}};
	["76"]	= {KillEffects = {"Blue Slice"}};
	["77"]	= {Armors = {"Miner"}};
	["78"]	= {Backpacks = {"Unicorn"}};
	["79"]	= {Currency	= {"100 Tickets"}};
	["80"]	= {Auras = {"Demon"}};
	["81"]	= {Hats = {"Red Paintball Mask"}};
	["82"]	= {XPBoost = {"10% XP Boost"}};
	["83"]	= {KillEffects = {"RIP"}};
	["84"]	= {Currency	= {"100 Tickets"}};
	["85"]	= {Outfits = {"Lava Cat Hoodie"}; Hats = {"Lava Cat Hood"}; Faces = {"Snarl"}};
	["86"]	= {Auras = {"Flaming Head"}};
	["87"]	= {Hats = {"Winter Centurion"}};
	["88"]	= {Emotes = {"Box"}};
	["89"]	= {Currency	= {"100 Tickets"}};
	["90"]	= {Faces = {"Cyclops"}};
	
	["91"]	= {Outfits = {"Kitsune"}; Hats = {"Kitsune Mask", "Kitsune Hair"}};
	["92"]	= {KillEffects = {"Burn"}};
	["93"]	= {Backpacks = {"Boombox"}};
	["94"]	= {Auras = {"Hack"}};
	["95"]	= {KillEffects = {"Medusa"}};
	["96"]	= {Hats = {"Valkyrie Shades"}};
	["97"]	= {Emotes = {"Glitch"}};
	["98"]	= {Hats = {"Clockwork Shades"}};
	["99"]	= {Outfits = {"Neon Demon"}; Hats = {"Neon Demon"}; Faces = {"Sunglasses"}};
	["100"]	= {Outfits = {"Hacker"}; Hats = {"Hacker"}; Faces = {"Retro Smile"}};
}